version: '3.4'

services:
  aspnetsqldocker:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - FilmConnection=server=sqldbService;Database=FilmDb;User Id=sa;Password=BigPassw0rd
    ports:
      - "5200:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

