version: '3.4'

services:


  sqldata:
    environment:
      - SA_PASSWORD=2Secure*Password2
      - ACCEPT_EULA=Y
    restart: always
    ports:
      - "1433:1433"  
    volumes:
      - film-sqldata:/var/opt/mssql
  aspnetsqldocker:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:DefaultConnection=Server=sqldata;Database=FilmDB;User Id=sa;Password=2Secure*Password2"
    depends_on:
      - sqldata
    ports:
      - "8012:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

volumes:
  film-sqldata:
    external: false