version: '3.4'

services:
  sqldbService:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: "BigPassw0rd"
    ports:
      - "1403:1433"

  aspnetsqldocker:
    image: ${DOCKER_REGISTRY-}aspnetsqldocker
    build:
      context: .
      dockerfile: AspNetSqlDocker/Dockerfile
    depends_on:
      - sqldbService